//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintVendorList.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7047/DynamicsNAV/WS/CRONUS%20International%20Ltd/SystemService")]
        public string PrintVendorList_NAVService_SystemService {
            get {
                return ((string)(this["PrintVendorList_NAVService_SystemService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7047/DynamicsNAV/WS/CRONUS%20International%20Ltd/Codeunit/Mobile" +
            "_Sales_Management")]
        public string PrintVendorList_NAVService_Mobile_Sales_Management {
            get {
                return ((string)(this["PrintVendorList_NAVService_Mobile_Sales_Management"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7047/DynamicsNAV/WS/CRONUS%20International%20Ltd/Page/Vendor")]
        public string PrintVendorList_NAVService_Vendor_Service {
            get {
                return ((string)(this["PrintVendorList_NAVService_Vendor_Service"]));
            }
        }
    }
}
